// <auto-generated />
using System;
using AdminVentas.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SevillaAdminVentas.Api.Migrations
{
    [DbContext(typeof(BDGestorVentasContext))]
    [Migration("20200816155646_TestMigration")]
    partial class TestMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatAmbitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("CatAmbitType");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatInvoiceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("CatInvoiceStatus");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatInvoiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("CatInvoiceType");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("CatStatus");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatTaxType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("CatTaxType");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("CityId");

                    b.Property<string>("ComertialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("Cp")
                        .HasColumnName("CP");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnName("RFC")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<int>("StateId");

                    b.Property<int>("StatusId")
                        .HasColumnName("StatusID");

                    b.Property<string>("TaxResidence")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Folio");

                    b.Property<string>("Rcfreceiver")
                        .IsRequired()
                        .HasColumnName("RCFReceiver")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("StatusId");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<int>("TypeId")
                        .HasColumnName("TypeID");

                    b.Property<int>("UserId");

                    b.Property<byte[]>("Uuid")
                        .IsRequired()
                        .HasColumnName("UUID")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("Idnumber")
                        .IsRequired()
                        .HasColumnName("IDNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProdServKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("StatusId");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UnitKey")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.Product2Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId");

                    b.Property<int>("TaxId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TaxId");

                    b.ToTable("Product2Tax");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FactorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("FeeRate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<int>("StatusId");

                    b.Property<string>("TaxKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("TypeAmbitId");

                    b.Property<int>("TypeId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeAmbitId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Tax");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.Customer", b =>
                {
                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatStatus", "Status")
                        .WithMany("Customer")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Customer_CatStatus");

                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.User", "User")
                        .WithMany("Customer")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Customer_User");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.Invoice", b =>
                {
                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatInvoiceStatus", "Status")
                        .WithMany("Invoice")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Invoice_CatStatusInvoice");

                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatInvoiceType", "Type")
                        .WithMany("Invoice")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Invoice_CatTypeInvoice");

                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.User", "User")
                        .WithMany("Invoice")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Invoice_User");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.Product2Tax", b =>
                {
                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.Product", "Product")
                        .WithMany("Product2Tax")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Invoice2Tax_Product");

                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.Tax", "Tax")
                        .WithMany("Product2Tax")
                        .HasForeignKey("TaxId")
                        .HasConstraintName("FK_Invoice2Tax_Tax");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.Tax", b =>
                {
                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatStatus", "Status")
                        .WithMany("Tax")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Tax_CatStatus");

                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatAmbitType", "TypeAmbit")
                        .WithMany("Tax")
                        .HasForeignKey("TypeAmbitId")
                        .HasConstraintName("FK_Tax_CatAmbitType");

                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatTaxType", "Type")
                        .WithMany("Tax")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Tax_CatTaxType");

                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.User", "User")
                        .WithMany("Tax")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Tax_User");
                });

            modelBuilder.Entity("AdminVentas.DataAccess.Contracts.Entities.Invoice.User", b =>
                {
                    b.HasOne("AdminVentas.DataAccess.Contracts.Entities.Invoice.CatStatus", "Status")
                        .WithMany("User")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_User_CatStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
